[project]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "Add a short description here"
name = "ludens-engine"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.1.0.dev2025011405,<26"
pygfx = ">=0.7.0,<0.8"

[pypi-dependencies]
glfw = ">=2.8.0, <3"

[system-requirements]
linux = "4.4"
libc = { family = "glibc", version = "2.28" }